import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HIP Bulgaria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-slate-200 antialiased'>
      <div className='container max-w-7xl mx-auto h-full bg-white'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
